# # 處理所有未定義網域的 80 埠請求
# server {
#     listen 80;
#     server_name _;
#     return 444; # 直接中斷連線，不回應任何資訊
# }

# # 處理所有未定義網域的 443 埠請求
# server {
#     listen 443 ssl;
#     server_name _;
    
#     # 仍需提供憑證才能啟動
#     ssl_certificate           /etc/nginx/ssl/server.crt;
#     ssl_certificate_key       /etc/nginx/ssl/server.key;
    
#     return 444;
# }

# 攔截所有進入 80 port 的 HTTP 請求
server {
    # default_server 標示為預設攔截起點，所有未命中特定 server_name 的皆會走此區塊
    listen 80 default_server;
    
    # 底線表示「匹配所有未被其他 server 宣告的網域名稱」
    server_name _;

    # 301 永久導向，自動帶著原本的 Host($host) 與 路徑($request_uri) 跳轉為 HTTPS
    return 301 https://$host$request_uri;
}

# (可選安全機制) 攔截未知的 HTTPS 請求 (無效域名跳轉保護)
server {
    listen 443 ssl default_server;
    server_name _;

    # SSL 連線就算是被阻擋，還是必須先提供一個墊底的預設憑證，才能成功建立交握
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # Nginx 特定指令：回傳 444 表示「直接切斷連線 (No Response)」，以擋掉網路掃描或直接使用 IP 連入的要求
    return 444;
}
