# upstream sonar_srv {
#     server sonarqube:9000;
# }

# server {
#     listen 80;
#     server_name sonarqube.local;
#     return 301 https://$host$request_uri;
# }

# server {
#     listen 443 ssl;
#     server_name sonarqube.local;

#     ssl_certificate           /etc/nginx/ssl/fullchain.pem;
#     ssl_certificate_key       /etc/nginx/ssl/privkey.pem;

#     proxy_set_header Host              $host;
#     proxy_set_header X-Real-IP         $remote_addr;
#     proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto  https;

#     location / {
#         proxy_pass         http://sonar_srv;
#         proxy_redirect     http:// https://;

#         # SonarQube 分析大型專案時需要較大的緩衝區
#         client_max_body_size 128M;
#         proxy_connect_timeout 150;
#         proxy_send_timeout    150;
#         proxy_read_timeout    150;
#     }
# }

server {
    listen 443 ssl;
    
    # 綁定給 SonarQube 專屬的網域
    server_name sonarqube.local;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # SonarQube 官方預設運行對外的 port 是 9000
        proxy_pass http://my-sonarqube:9000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 重要：SonarQube 長期運作下經常會需要上傳大量的代碼掃描與綜合報告壓縮檔
        # 強烈建議放大上傳限制容量，以防 CI/CD 流程斷線 (數值視您的專案量而定)
        client_max_body_size 100m;
        
        # (選配) 若您的報告掃碼分析量過大，連線曾發生 nginx 報告 504 timeout，也可延長代理連接等待時間
        # proxy_read_timeout 300s;
        # proxy_connect_timeout 300s;
    }
}
